# Generated by Django 3.1.5 on 2021-01-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('catagories', models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6)),
                ('item_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AddStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityNo', models.IntegerField()),
                ('quantityUnit', models.CharField(choices=[('KG', 'KG'), ('ltr', 'liter'), ('unit', 'unit')], default='green', max_length=6)),
                ('costPrice', models.FloatField()),
                ('sellingPrice', models.FloatField()),
                ('item_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
