# Generated by Django 3.1.5 on 2021-01-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210124_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstore',
            old_name='item_name',
            new_name='item',
        ),
    ]
